tboard = {
    "board": [
        [
            ["orange", ["pink", "light"]],
            ["blue", ["orange", "light"]],
            ["purple", ["green", "light"]],
            ["pink", ["red", "light"]],
            ["yellow", ["purple", "light"]],
            ["red", ["blue", "light"]],
            ["green", ["brown", "light"]],
            ["brown", ["yellow", "light"]],
        ],
        [
            ["red", "null"],
            ["orange", "null"],
            ["pink", "null"],
            ["green", "null"],
            ["blue", "null"],
            ["yellow", "null"],
            ["brown", "null"],
            ["purple", "null"],
        ],
        [
            ["green", "null"],
            ["pink", "null"],
            ["orange", "null"],
            ["red", "null"],
            ["purple", "null"],
            ["brown", "null"],
            ["yellow", "null"],
            ["blue", "null"],
        ],
        [
            ["pink", "null"],
            ["purple", "null"],
            ["blue", "null"],
            ["orange", "null"],
            ["brown", "null"],
            ["green", "null"],
            ["red", "null"],
            ["yellow", "null"],
        ],
        [
            ["yellow", "null"],
            ["red", "null"],
            ["green", "null"],
            ["brown", "null"],
            ["orange", "null"],
            ["blue", "null"],
            ["purple", "null"],
            ["pink", "null"],
        ],
        [
            ["blue", "null"],
            ["yellow", "null"],
            ["brown", "null"],
            ["purple", "null"],
            ["red", "null"],
            ["orange", "null"],
            ["pink", "null"],
            ["green", "null"],
        ],
        [
            ["purple", "null"],
            ["brown", "null"],
            ["yellow", "null"],
            ["blue", "null"],
            ["green", "null"],
            ["pink", "null"],
            ["orange", "null"],
            ["red", "null"],
        ],
        [
            ["brown", ["yellow", "dark"]],
            ["green", ["green", "dark"]],
            ["red", ["orange", "dark"]],
            ["yellow", ["purple", "dark"]],
            ["pink", ["red", "dark"]],
            ["purple", ["brown", "dark"]],
            ["blue", ["blue", "dark"]],
            ["orange", ["pink", "dark"]],
        ],
    ],
    "color": "red",
    "current": 0,
    "players": ["LUR", "FKY"],
}
